export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const MULTI_REGISTER_REQUEST = "MULTI_REGISTER_REQUEST"
export const MULTI_REGISTER_SUCCESS = "MULTI_REGISTER_SUCCESS"
export const MULTI_REGISTER_FAIL = "MULTI_REGISTER_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"

export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST"
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS"
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"
export const SET_USER_LIST = "SET_USER_LIST"
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const SINGLE_USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const SINGLE_USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const SINGLE_USER_LIST_FAIL = "USER_LIST_FAIL"
export const SINGLE_SET_USER_LIST = "SET_USER_LIST"

export const GET_COVER_LETTER_REQUEST = "GET_COVER_LETTER_REQUEST"
export const GET_COVER_LETTER_SUCCESS = "GET_COVER_LETTER_SUCCESS"
export const GET_COVER_LETTER_FAIL = "GET_COVER_LETTER_FAIL"

export const GET_IMAGE_REQUEST = "GET_IMAGE_REQUEST"
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS"
export const GET_IMAGE_FAIL = "GET_IMAGE_FAIL"

export const USER_DRIVE_NAME_REQUEST = "USER_DRIVE_NAME_REQUEST"
export const USER_DRIVE_NAME_SUCCESS = "USER_DRIVE_NAME_SUCCESS"
export const USER_DRIVE_NAME_FAIL = "USER_DRIVE_NAME_FAIL"
export const SET_DRIVE_NAME = "SET_DRIVE_NAME"

export const USER_INTERVIEW_COMPLETED_REQUEST = "USER_INTERVIEW_COMPLETED_REQUEST"
export const USER_INTERVIEW_COMPLETED_SUCCESS = "USER_INTERVIEW_COMPLETED_SUCCESS"
export const USER_INTERVIEW_COMPLETED_FAIL = "USER_INTERVIEW_COMPLETED_FAIL"
export const SET_INTERVIEW_COMPLETED = "SET_INTERVIEW_COMPLETED"

export const USER_INTERVIEW_STARTENDTIME_REQUEST = "USER_INTERVIEW_STARTENDTIME_REQUEST"
export const USER_INTERVIEW_STARTENDTIME_SUCCESS = "USER_INTERVIEW_STARTENDTIME_SUCCESS"
export const USER_INTERVIEW_STARTENDTIME_FAIL = "USER_INTERVIEW_STARTENDTIME_FAIL"
export const SET_INTERVIEW_STARTENDTIME = "SET_INTERVIEW_STARTENDTIME"

export const REQDFIELDS_REQUEST = "REQDFIELDS_REQUEST"
export const REQDFIELDS_SUCCESS = "REQDFIELDS_SUCCESS"
export const REQDFIELDS_FAIL = "REQDFIELDS_FAIL"
export const SET_REQDFIELDS = "SET_REQDFIELDS"

export const MULTI_JD_UPLOAD_REQUEST = "MULTI_JD_UPLOAD_REQUEST"
export const MULTI_JD_UPLOAD_SUCCESS = "MULTI_JD_UPLOAD_SUCCESS"
export const MULTI_JD_UPLOAD_FAIL = "MULTI_JD_UPLOAD_FAIL"

export const GET_ALL_JD_REQUEST = "GET_ALL_JD_REQUEST"
export const GET_ALL_JD_SUCCESS = "GET_ALL_JD_SUCCESS"
export const GET_ALL_JD_FAIL = "GET_ALL_JD_FAIL"

export const USER_IMAGE_COVERLETTER_UPLOAD_REQUEST = "USER_IMAGE_COVERLETTER_UPLOAD_REQUEST"
export const USER_IMAGE_COVERLETTER_UPLOAD_SUCCESS = "USER_IMAGE_COVERLETTER_UPLOAD_SUCCESS"
export const USER_IMAGE_COVERLETTER_UPLOAD_FAIL = "USER_IMAGE_COVERLETTER_UPLOAD_FAIL"

export const USER_JD_LIST_REQUEST = "USER_JD_LIST_REQUEST"
export const USER_JD_LIST_SUCCESS = "USER_JD_LIST_SUCCESS"
export const USER_JD_LIST_FAIL = "USER_JD_LIST_FAIL"

export const ASSIGN_INTERVIEW_START_TIME_REQUEST = "ASSIGN_INTERVIEW_START_TIME_REQUEST"
export const ASSIGN_INTERVIEW_START_TIME_SUCCESS = "ASSIGN_INTERVIEW_START_TIME_SUCCESS"
export const ASSIGN_INTERVIEW_START_TIME_FAIL = "ASSIGN_INTERVIEW_START_TIME_FAIL"
export const SET_ASSIGN_INTERVIEW_START_TIME = "SET_ASSIGN_INTERVIEW_START_TIME"

export const ASSIGN_INTERVIEW_END_TIME_REQUEST = "ASSIGN_INTERVIEW_END_TIME_REQUEST"
export const ASSIGN_INTERVIEW_END_TIME_SUCCESS = "ASSIGN_INTERVIEW_END_TIME_SUCCESS"
export const ASSIGN_INTERVIEW_END_TIME_FAIL = "ASSIGN_INTERVIEW_END_TIME_FAIL"
export const SET_ASSIGN_INTERVIEW_END_TIME = "SET_ASSIGN_INTERVIEW_END_TIME"

export const ASSIGN_INTERVIEW_DATE_REQUEST = "ASSIGN_INTERVIEW_INTERVIEW_DATE_REQUEST"
export const ASSIGN_INTERVIEW_DATE_SUCCESS = "ASSIGN_INTERVIEW_INTERVIEW_DATE_SUCCESS"
export const ASSIGN_INTERVIEW_DATE_FAIL = "ASSIGN_INTERVIEW_INTERVIEW_DATE_FAIL"
export const SET_ASSIGN_INTERVIEW_DATE = "SET_ASSIGN_INTERVIEW_DATE"

export const COVERLETTER_UPLOAD_REQUEST = 'COVERLETTER_UPLOAD_REQUEST';  
export const COVERLETTER_UPLOAD_SUCCESS = 'COVERLETTER_UPLOAD_SUCCESS';  
export const COVERLETTER_UPLOAD_FAIL = 'COVERLETTER_UPLOAD_FAIL';  
  
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';  
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';  
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL';  

export const FILTERED_USER_LIST_REQUEST = "FILTERED_USER_LIST_REQUEST"
export const FILTERED_USER_LIST_SUCCESS = "FILTERED_USER_LIST_SUCCESS"
export const FILTERED_USER_LIST_FAIL = "FILTERED_USER_LIST_FAIL"
export const SET_FILTERED_USER_LIST = "SET_FILTERED_USER_LIST"

export const GET_CHATLOG_REQUEST = "GET_CHATLOG_REQUEST"
export const GET_CHATLOG_SUCCESS = "GET_CHATLOG_SUCCESS"
export const GET_CHATLOG_FAIL = "GET_CHATLOG_FAIL"
export const SET_CHATLOG = "SET_CHATLOG"

export const INTERVIEWRECORDING_UPLOAD_REQUEST = 'INTERVIEWRECORDING_UPLOAD_REQUEST';  
export const INTERVIEWRECORDING_UPLOAD_SUCCESS = 'INTERVIEWRECORDING_UPLOAD_SUCCESS';  
export const INTERVIEWRECORDING_UPLOAD_FAIL = 'INTERVIEWRECORDING_UPLOAD_FAIL'; 

export const GET_INTERVIEWRECORDING_REQUEST = "GET_INTERVIEWRECORDING_REQUEST"
export const GET_INTERVIEWRECORDING_SUCCESS = "GET_INTERVIEWRECORDING_SUCCESS"
export const GET_INTERVIEWRECORDING_FAIL = "GET_INTERVIEWRECORDING_FAIL"

export const ATTENDANCE_REQUEST = "ATTENDANCE_REQUEST"
export const ATTENDANCE_SUCCESS = "ATTENDANCE_SUCCESS"
export const ATTENDANCE_FAIL = "ATTENDANCE_FAIL"
export const SET_ATTENDANCE = "SET_ATTENDANCE"

export const GET_CONFSCORE_REQUEST = "GET_CONFSCORE_REQUEST"
export const GET_CONFSCORE_SUCCESS = "GET_CONFSCORE_SUCCESS"
export const GET_CONFSCORE_FAIL = "GET_CONFSCORE_FAIL"
export const SET_CONFSCORE = "SET_CONFSCORE"

export const GET_CHECK_IMG_EXISTS_REQUEST = "GET_CHECK_IMG_EXISTS_REQUEST"
export const GET_CHECK_IMG_EXISTS_SUCCESS = "GET_CHECK_IMG_EXISTS_SUCCESS"
export const GET_CHECK_IMG_EXISTS_FAIL = "GET_CHECK_IMG_EXISTS_FAIL"
export const SET_CHECK_IMG_EXISTS = "SET_CHECK_IMG_EXISTS_"

export const GET_DRIVE_AND_SLOT_REQUEST = "GET_DRIVE_AND_SLOT_REQUEST"
export const GET_DRIVE_AND_SLOT_SUCCESS = "GET_DRIVE_AND_SLOT_SUCCESS"
export const GET_DRIVE_AND_SLOT_FAIL = "GET_DRIVE_AND_SLOT_FAIL"
export const SET_DRIVE_AND_SLOT = "SET_DRIVE_AND_SLOT"